CREATE TABLE products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  tagline TEXT NOT NULL,
  description TEXT NOT NULL,
  ingredients TEXT NOT NULL, -- JSON array
  price_cents INTEGER NOT NULL,
  square_url TEXT NOT NULL,
  color TEXT NOT NULL CHECK(color IN ('clover', 'lavender', 'yellow-crayon', 'olive')),
  image_key TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1
);

INSERT INTO products (id, name, tagline, description, ingredients, price_cents, square_url, color, image_key, sort_order) VALUES
  ('pink-pop-potion',                'Pink Pop Potion!',      'Smart sips for little lips',         'Our signature pink blend — gently sweet, fruity, and floral. A joyful herbal tisane that''s just the thing for an after-school sip.',              '["Chamomile","Apple","Strawberry","Hibiscus"]',  1500, 'https://drinkkidclover.square.site/product/pink-pop-potion-/YDHH3TSGMLYR47EYL2FJCF5X',                'clover',        'pink-pop-potion',                1),
  ('day-dreamer',                    'Day Dreamers',          'Smart sips for little lips',         'A soft, calming herbal tisane to ease busy little minds. Pour, snuggle, story, sleep.',                                                            '["Lemon Balm","Chamomile"]',                     1500, 'https://drinkkidclover.square.site/product/day-dreamer/44HRVATRJFX6LOBCLKSOEU4H',                       'lavender',      'day-dreamer',                    2),
  ('tiny-recess',                    'Tiny Recess',           'Smart sips for little lips',         'A bright, refreshing herbal tisane — a green little pick-me-up that''s lovely hot or iced.',                                                      '["Nettle","Apple","Spearmint"]',                 1500, 'https://drinkkidclover.square.site/product/tiny-recess/VT264GRFK33HVTBUEDNKE3H3',                       'yellow-crayon', 'tiny-recess',                    3),
  ('tigers-eye-ginger',              'Tiger''s Eye',          'Warm & ease',                        'A ginger tisane for warming and easing. Cars, boats & planes — know I''ve got your back.',                                                         '["Ginger root"]',                               600,  'https://drinkkidclover.square.site/product/tiger-s-eye-ginger/O6D3XV36UPKTPCVOFSGRKPAG',                 'yellow-crayon', 'tigers-eye-ginger',              4),
  ('crystal-cauldron-chamomile',     'Crystal Cauldron',      'Calm & soothe',                      'A chamomile tisane for calming and soothing. Small but mighty, like the elves.',                                                                   '["Chamomile"]',                                 600,  'https://drinkkidclover.square.site/product/crystal-cauldron-chamomile/ABGPBDV4RIZGEFQRW7X6KRCN',        'lavender',      'crystal-cauldron-chamomile',     5),
  ('dragonflies-society-rose-hips',  'Dragonflies Society',   'Nutritive & supportive',             'A rose hip tisane that''s nutritive and supportive. So much vitamin C, even the lemons are jealous.',                                              '["Rose hips"]',                                 600,  'https://drinkkidclover.square.site/product/dragonflies-society-rose-hips/VCDEPYATSGESA3A56CLTBAK6',      'clover',        'dragonflies-society-rose-hips',  6),
  ('griffins-gold-lemon-verbena',    'Griffin''s Gold',       'Brighten & calm',                    'A lemon verbena tisane for brightening and calming. Calls the sun on cloudy days!',                                                                '["Lemon verbena"]',                             600,  'https://drinkkidclover.square.site/product/griffin-s-gold-lemon-verbena/CL7DUASHVFUOJNB3PUZT6HBB',      'yellow-crayon', 'griffins-gold-lemon-verbena',    7),
  ('ogress-lantern-lemon-balm',      'Ogress''s Lantern',     'Relax & comfort',                    'A lemon balm tisane for relaxing and comforting. Sweetens the day — all the bees agree!',                                                          '["Lemon balm"]',                                600,  'https://drinkkidclover.square.site/product/ogress-s-lantern-lemon-balm/OHT4MA2H5XFX2EOOVOIRUHK6',      'olive',         'ogress-lantern-lemon-balm',      8),
  ('pixie-dust-peppermint',          'Pixie Dust',            'Rejuvenate & invigorate',            'A peppermint tisane for rejuvenating and invigorating. Find me in the garden, just like the fairies.',                                             '["Peppermint"]',                                600,  'https://drinkkidclover.square.site/product/pixie-dust-peppermint/5ETM363IZ5UHDPUOCJ3BS5AL',            'olive',         'pixie-dust-peppermint',          9),
  ('3-simples',                      '3 Simples',             'Build-your-own bundle · 15% off',    'Pick any three of our single-herb simples and save 15%. A lovely way to sample the apothecary.',                                                   '["Choose any 3 simples at checkout"]',          1500, 'https://drinkkidclover.square.site/product/3-simples/2HLU44IDTC32I6IKTATNR2SE',                         'lavender',      '3-simples',                      10),
  ('6-simples',                      '6 Simples',             'Build-your-own bundle · 20% off',    'Pick any six of our single-herb simples and save 20%. The full apothecary shelf in one go.',                                                       '["Choose any 6 simples at checkout"]',          2800, 'https://drinkkidclover.square.site/product/6-simples/IBC4MZLR4QULZ6N465MOQZR7',                         'clover',        '6-simples',                      11);
