/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouSummer2026RaffleRouteImport } from './routes/thank-you-summer-2026-raffle'
import { Route as ThankYouSlowdownRouteImport } from './routes/thank-you-slowdown'
import { Route as ThankYouEnoRiverRouteImport } from './routes/thank-you-eno-river'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LpSlugRouteImport } from './routes/lp/$slug'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth/complete-profile'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminLandingPagesRouteImport } from './routes/admin/landing-pages'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminCampaignsRouteImport } from './routes/admin/campaigns'

const ThankYouSummer2026RaffleRoute =
  ThankYouSummer2026RaffleRouteImport.update({
    id: '/thank-you-summer-2026-raffle',
    path: '/thank-you-summer-2026-raffle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThankYouSlowdownRoute = ThankYouSlowdownRouteImport.update({
  id: '/thank-you-slowdown',
  path: '/thank-you-slowdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouEnoRiverRoute = ThankYouEnoRiverRouteImport.update({
  id: '/thank-you-eno-river',
  path: '/thank-you-eno-river',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LpSlugRoute = LpSlugRouteImport.update({
  id: '/lp/$slug',
  path: '/lp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingPagesRoute = AdminLandingPagesRouteImport.update({
  id: '/landing-pages',
  path: '/landing-pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
  '/thank-you-eno-river': typeof ThankYouEnoRiverRoute
  '/thank-you-slowdown': typeof ThankYouSlowdownRoute
  '/thank-you-summer-2026-raffle': typeof ThankYouSummer2026RaffleRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/lp/$slug': typeof LpSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
  '/thank-you-eno-river': typeof ThankYouEnoRiverRoute
  '/thank-you-slowdown': typeof ThankYouSlowdownRoute
  '/thank-you-summer-2026-raffle': typeof ThankYouSummer2026RaffleRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/lp/$slug': typeof LpSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
  '/thank-you-eno-river': typeof ThankYouEnoRiverRoute
  '/thank-you-slowdown': typeof ThankYouSlowdownRoute
  '/thank-you-summer-2026-raffle': typeof ThankYouSummer2026RaffleRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/lp/$slug': typeof LpSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/events'
    | '/gallery'
    | '/join'
    | '/order-confirmed'
    | '/orders'
    | '/shop'
    | '/thank-you-eno-river'
    | '/thank-you-slowdown'
    | '/thank-you-summer-2026-raffle'
    | '/admin/campaigns'
    | '/admin/events'
    | '/admin/landing-pages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/logout'
    | '/lp/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/events'
    | '/gallery'
    | '/join'
    | '/order-confirmed'
    | '/orders'
    | '/shop'
    | '/thank-you-eno-river'
    | '/thank-you-slowdown'
    | '/thank-you-summer-2026-raffle'
    | '/admin/campaigns'
    | '/admin/events'
    | '/admin/landing-pages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/logout'
    | '/lp/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/events'
    | '/gallery'
    | '/join'
    | '/order-confirmed'
    | '/orders'
    | '/shop'
    | '/thank-you-eno-river'
    | '/thank-you-slowdown'
    | '/thank-you-summer-2026-raffle'
    | '/admin/campaigns'
    | '/admin/events'
    | '/admin/landing-pages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/auth/login'
    | '/auth/logout'
    | '/lp/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  JoinRoute: typeof JoinRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  OrdersRoute: typeof OrdersRoute
  ShopRoute: typeof ShopRoute
  ThankYouEnoRiverRoute: typeof ThankYouEnoRiverRoute
  ThankYouSlowdownRoute: typeof ThankYouSlowdownRoute
  ThankYouSummer2026RaffleRoute: typeof ThankYouSummer2026RaffleRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  LpSlugRoute: typeof LpSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you-summer-2026-raffle': {
      id: '/thank-you-summer-2026-raffle'
      path: '/thank-you-summer-2026-raffle'
      fullPath: '/thank-you-summer-2026-raffle'
      preLoaderRoute: typeof ThankYouSummer2026RaffleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you-slowdown': {
      id: '/thank-you-slowdown'
      path: '/thank-you-slowdown'
      fullPath: '/thank-you-slowdown'
      preLoaderRoute: typeof ThankYouSlowdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you-eno-river': {
      id: '/thank-you-eno-river'
      path: '/thank-you-eno-river'
      fullPath: '/thank-you-eno-river'
      preLoaderRoute: typeof ThankYouEnoRiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/landing-pages': {
      id: '/admin/landing-pages'
      path: '/landing-pages'
      fullPath: '/admin/landing-pages'
      preLoaderRoute: typeof AdminLandingPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLandingPagesRoute: typeof AdminLandingPagesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLandingPagesRoute: AdminLandingPagesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  JoinRoute: JoinRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  OrdersRoute: OrdersRoute,
  ShopRoute: ShopRoute,
  ThankYouEnoRiverRoute: ThankYouEnoRiverRoute,
  ThankYouSlowdownRoute: ThankYouSlowdownRoute,
  ThankYouSummer2026RaffleRoute: ThankYouSummer2026RaffleRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  LpSlugRoute: LpSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
