/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouSummer2026RaffleRouteImport } from './routes/thank-you-summer-2026-raffle'
import { Route as ThankYouSlowdownRouteImport } from './routes/thank-you-slowdown'
import { Route as ThankYouEnoRiverRouteImport } from './routes/thank-you-eno-river'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const ThankYouSummer2026RaffleRoute =
  ThankYouSummer2026RaffleRouteImport.update({
    id: '/thank-you-summer-2026-raffle',
    path: '/thank-you-summer-2026-raffle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThankYouSlowdownRoute = ThankYouSlowdownRouteImport.update({
  id: '/thank-you-slowdown',
  path: '/thank-you-slowdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouEnoRiverRoute = ThankYouEnoRiverRouteImport.update({
  id: '/thank-you-eno-river',
  path: '/thank-you-eno-river',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
  '/thank-you-eno-river': typeof ThankYouEnoRiverRoute
  '/thank-you-slowdown': typeof ThankYouSlowdownRoute
  '/thank-you-summer-2026-raffle': typeof ThankYouSummer2026RaffleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
  '/thank-you-eno-river': typeof ThankYouEnoRiverRoute
  '/thank-you-slowdown': typeof ThankYouSlowdownRoute
  '/thank-you-summer-2026-raffle': typeof ThankYouSummer2026RaffleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/orders': typeof OrdersRoute
  '/shop': typeof ShopRoute
  '/thank-you-eno-river': typeof ThankYouEnoRiverRoute
  '/thank-you-slowdown': typeof ThankYouSlowdownRoute
  '/thank-you-summer-2026-raffle': typeof ThankYouSummer2026RaffleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/events'
    | '/gallery'
    | '/join'
    | '/order-confirmed'
    | '/orders'
    | '/shop'
    | '/thank-you-eno-river'
    | '/thank-you-slowdown'
    | '/thank-you-summer-2026-raffle'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/events'
    | '/gallery'
    | '/join'
    | '/order-confirmed'
    | '/orders'
    | '/shop'
    | '/thank-you-eno-river'
    | '/thank-you-slowdown'
    | '/thank-you-summer-2026-raffle'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/events'
    | '/gallery'
    | '/join'
    | '/order-confirmed'
    | '/orders'
    | '/shop'
    | '/thank-you-eno-river'
    | '/thank-you-slowdown'
    | '/thank-you-summer-2026-raffle'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  JoinRoute: typeof JoinRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  OrdersRoute: typeof OrdersRoute
  ShopRoute: typeof ShopRoute
  ThankYouEnoRiverRoute: typeof ThankYouEnoRiverRoute
  ThankYouSlowdownRoute: typeof ThankYouSlowdownRoute
  ThankYouSummer2026RaffleRoute: typeof ThankYouSummer2026RaffleRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you-summer-2026-raffle': {
      id: '/thank-you-summer-2026-raffle'
      path: '/thank-you-summer-2026-raffle'
      fullPath: '/thank-you-summer-2026-raffle'
      preLoaderRoute: typeof ThankYouSummer2026RaffleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you-slowdown': {
      id: '/thank-you-slowdown'
      path: '/thank-you-slowdown'
      fullPath: '/thank-you-slowdown'
      preLoaderRoute: typeof ThankYouSlowdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you-eno-river': {
      id: '/thank-you-eno-river'
      path: '/thank-you-eno-river'
      fullPath: '/thank-you-eno-river'
      preLoaderRoute: typeof ThankYouEnoRiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  JoinRoute: JoinRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  OrdersRoute: OrdersRoute,
  ShopRoute: ShopRoute,
  ThankYouEnoRiverRoute: ThankYouEnoRiverRoute,
  ThankYouSlowdownRoute: ThankYouSlowdownRoute,
  ThankYouSummer2026RaffleRoute: ThankYouSummer2026RaffleRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
